# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# Templates
#   Card.create(name:, deck:, strength:, role:, combatType:, cardAbility:, description:)
#   Deck.create(deckName:, faction:, user:)
#   DeckCard.create(deck:, card:)
#   User.create(username:)

# All the cards
Card.create(name:"Arachas", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Arachas", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Arachas", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Arachas Behemoth", deck:"Monsters", role:"Basic", strength:6, combatType:"Siege", cardAbility:"Muster", description:"")
Card.create(name:"Botchling", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Celaeno Harpy", deck:"Monsters", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Cockatrice", deck:"Monsters", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Crone Brewess", deck:"Monsters", role:"Basic", strength:6, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Crone Weavess", deck:"Monsters", role:"Basic", strength:6, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Crone Whispess", deck:"Monsters", role:"Basic", strength:6, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Draug", deck:"Monsters", role:"Basic", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Earth Elemental", deck:"Monsters", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Endrega", deck:"Monsters", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Eredin Bringer of Death", deck:"Monsters", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Discard 2 draw 1", description:"")
Card.create(name:"Eredin Commander of the Red Riders", deck:"Monsters", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Pick any weather", description:"")
Card.create(name:"Eredin Destroyer of Worlds", deck:"Monsters", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Medic", description:"")
Card.create(name:"Eredin King of the Wild Hunt", deck:"Monsters", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Horn Close Combat", description:"")
Card.create(name:"Fiend", deck:"Monsters", role:"Basic", strength:6, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Fire Elemental", deck:"Monsters", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Foglet", deck:"Monsters", role:"Basic", strength:2, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Forktail", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Frightener", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Gargoyle", deck:"Monsters", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Ghoul", deck:"Monsters", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Ghoul", deck:"Monsters", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Ghoul", deck:"Monsters", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Grave Hag", deck:"Monsters", role:"Basic", strength:5, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Griffin", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Harpy", deck:"Monsters", role:"Basic", strength:2, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Ice Giant", deck:"Monsters", role:"Basic", strength:5, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Imlerith", deck:"Monsters", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Kayran", deck:"Monsters", role:"Hero", strength:8, combatType:"Range", cardAbility:"Morale, Immune to special", description:"")
Card.create(name:"Leshen", deck:"Monsters", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Nekker", deck:"Monsters", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Nekker", deck:"Monsters", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Nekker", deck:"Monsters", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Plague Maiden", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Vampire Bruxa", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Vampire Ekimmara", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Vampire Fleder", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Vampire Garkain", deck:"Monsters", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Vampire Katakan", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Werewolf", deck:"Monsters", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Wyvern", deck:"Monsters", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Avallac'h (A.K.A Mysterious Elf)", deck:"Neutral", role:"Hero", strength:0, combatType:"Melee", cardAbility:"Spy, Immune to special", description:"")
Card.create(name:"Biting Frost", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero melee to 1", description:"")
Card.create(name:"Biting Frost", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero melee to 1", description:"")
Card.create(name:"Biting Frost", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero melee to 1", description:"")
Card.create(name:"Cirilla Fiona Elen Rianno", deck:"Neutral", role:"Hero", strength:15, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Clear Weather", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Removes all weather", description:"")
Card.create(name:"Clear Weather", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Removes all weather", description:"")
Card.create(name:"Commander's Horn", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Double the strength of row", description:"")
Card.create(name:"Commander's Horn", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Double the strength of row", description:"")
Card.create(name:"Commander's Horn", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Double the strength of row", description:"")
Card.create(name:"Dandelion", deck:"Neutral", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Commander's Horn", description:"")
Card.create(name:"Decoy", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Swap with a non-hero card", description:"")
Card.create(name:"Decoy", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Swap with a non-hero card", description:"")
Card.create(name:"Decoy", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Swap with a non-hero card", description:"")
Card.create(name:"Emiel Regis Rohellec Terzieff", deck:"Neutral", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Geralt of Rivia", deck:"Neutral", role:"Hero", strength:15, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Impenetrable Fog", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero range to 1", description:"")
Card.create(name:"Impenetrable Fog", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero range to 1", description:"")
Card.create(name:"Impenetrable Fog", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero range to 1", description:"")
Card.create(name:"Scorch", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Destroys the strongest non-hero card", description:"")
Card.create(name:"Scorch", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Destroys the strongest non-hero card", description:"")
Card.create(name:"Scorch", deck:"Neutral", role:"Special", strength:0, combatType:"Special", cardAbility:"Destroys the strongest non-hero card", description:"")
Card.create(name:"Torrential Rain", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero siege to 1", description:"")
Card.create(name:"Torrential Rain", deck:"Neutral", role:"Special", strength:0, combatType:"Weather", cardAbility:"Sets all non-hero siege to 1", description:"")
Card.create(name:"Triss Merigold", deck:"Neutral", role:"Hero", strength:7, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Vesemir", deck:"Neutral", role:"Basic", strength:6, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Villentretenmerth", deck:"Neutral", role:"Basic", strength:7, combatType:"Melee", cardAbility:"Destroy opponent's strongest melee if melee +10", description:"")
Card.create(name:"Yennefer of Vengerberg", deck:"Neutral", role:"Hero", strength:7, combatType:"Range", cardAbility:"Medic, Immune to special", description:"")
Card.create(name:"Zoltan Chivay", deck:"Neutral", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Albrich", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Assire var Anahid", deck:"Nilfgaard", role:"Basic", strength:6, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Black Infantry Archer", deck:"Nilfgaard", role:"Basic", strength:10, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Black Infantry Archer", deck:"Nilfgaard", role:"Basic", strength:10, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Cahir Mawr Dyffryn aep Ceallach", deck:"Nilfgaard", role:"Basic", strength:6, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Cynthia", deck:"Nilfgaard", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Emhry var Emrels His Imperial Majesty", deck:"Nilfgaard", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Rain", description:"")
Card.create(name:"Emhry var Emrels the White Flame", deck:"Nilfgaard", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Cancel opponent's leader effect", description:"")
Card.create(name:"Emhyr var Emreis Emperor of Nilfgaard", deck:"Nilfgaard", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Look at 3 of the opponent's cards", description:"")
Card.create(name:"Emhyr var Emreis the Relentless", deck:"Nilfgaard", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Draw card from opponent's discard pile", description:"")
Card.create(name:"Etolian Auxiliary Archers", deck:"Nilfgaard", role:"Basic", strength:1, combatType:"Range", cardAbility:"Medic", description:"")
Card.create(name:"Etolian Auxiliary Archers", deck:"Nilfgaard", role:"Basic", strength:1, combatType:"Range", cardAbility:"Medic", description:"")
Card.create(name:"Fringilla Vigo", deck:"Nilfgaard", role:"Basic", strength:6, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Heavy Zerrikanian Fire Scorpion", deck:"Nilfgaard", role:"Basic", strength:10, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Impera Brigade Guard", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Impera Brigade Guard", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Impera Brigade Guard", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Impera Brigade Guard", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Letho of Gulet", deck:"Nilfgaard", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Menno Coehoorn", deck:"Nilfgaard", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Morteisen", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Morvran Voorhis", deck:"Nilfgaard", role:"Hero", strength:10, combatType:"Siege", cardAbility:"Immune to special", description:"")
Card.create(name:"Nausicaa Cavalry Rider", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Nausicaa Cavalry Rider", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Nausicaa Cavalry Rider", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Puttkammer", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Rainfarn", deck:"Nilfgaard", role:"Basic", strength:4, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Renuald aep Matsen", deck:"Nilfgaard", role:"Basic", strength:5, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Rotten Mangonel", deck:"Nilfgaard", role:"Basic", strength:3, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Shilard Fitz-Oesterlen", deck:"Nilfgaard", role:"Basic", strength:7, combatType:"Melee", cardAbility:"Spy", description:"")
Card.create(name:"Siege Engineer", deck:"Nilfgaard", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Siege Technician", deck:"Nilfgaard", role:"Basic", strength:0, combatType:"Siege", cardAbility:"Medic", description:"")
Card.create(name:"Stefan Skellen", deck:"Nilfgaard", role:"Basic", strength:9, combatType:"Melee", cardAbility:"Spy", description:"")
Card.create(name:"Sweers", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Tibor Eggebracht", deck:"Nilfgaard", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Vanhemar", deck:"Nilfgaard", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Vattier de Rideaux", deck:"Nilfgaard", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Spy", description:"")
Card.create(name:"Vreemde", deck:"Nilfgaard", role:"Basic", strength:2, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Young Emissary", deck:"Nilfgaard", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Young Emissary", deck:"Nilfgaard", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Zerrikanian Fire Scorpion", deck:"Nilfgaard", role:"Basic", strength:5, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Blue Stripes Commando", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Blue Stripes Commando", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Blue Stripes Commando", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Catapult", deck:"Northern Realms", role:"Basic", strength:8, combatType:"Siege", cardAbility:"Bond", description:"")
Card.create(name:"Catapult", deck:"Northern Realms", role:"Basic", strength:8, combatType:"Siege", cardAbility:"Bond", description:"")
Card.create(name:"Crinfrid Reavers Dragon Hunter", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Range", cardAbility:"Bond", description:"")
Card.create(name:"Crinfrid Reavers Dragon Hunter", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Range", cardAbility:"Bond", description:"")
Card.create(name:"Crinfrid Reavers Dragon Hunter", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Range", cardAbility:"Bond", description:"")
Card.create(name:"Dethmold", deck:"Northern Realms", role:"Basic", strength:6, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Dun Banner Medic", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Siege", cardAbility:"Medic", description:"")
Card.create(name:"Esterad Thyssen", deck:"Northern Realms", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Foltest King of Temeria", deck:"Northern Realms", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Fog", description:"")
Card.create(name:"Foltest Lord Commander of the North", deck:"Northern Realms", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Clear Weather", description:"")
Card.create(name:"Foltest the Siegemaster", deck:"Northern Realms", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Horn on Siege", description:"")
Card.create(name:"Foltest the Steel-Forged", deck:"Northern Realms", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Scorch Siege if +10", description:"")
Card.create(name:"John Natalis", deck:"Northern Realms", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Kaedweni Siege Expert", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Siege", cardAbility:"Morale", description:"")
Card.create(name:"Kaedweni Siege Expert", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Siege", cardAbility:"Morale", description:"")
Card.create(name:"Kaedweni Siege Expert", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Siege", cardAbility:"Morale", description:"")
Card.create(name:"Keira Metz", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Philippa Eilhart", deck:"Northern Realms", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Poor Fucking Infantry", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Poor Fucking Infantry", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Poor Fucking Infantry", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Melee", cardAbility:"Bond", description:"")
Card.create(name:"Prince Stennis", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Spy", description:"")
Card.create(name:"Redanian Foot Soldier", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Redanian Foot Soldier", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Sabrina Glevissig", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Sheldon Skaggs", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Siege Tower", deck:"Northern Realms", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Siegfried of Denesle", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Sigismund Dijkstra", deck:"Northern Realms", role:"Basic", strength:4, combatType:"Melee", cardAbility:"Spy", description:"")
Card.create(name:"Sıĺ e de Tansarville", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Thaler", deck:"Northern Realms", role:"Basic", strength:1, combatType:"Siege", cardAbility:"Spy", description:"")
Card.create(name:"Trebuchet", deck:"Northern Realms", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Trebuchet", deck:"Northern Realms", role:"Basic", strength:6, combatType:"Siege", cardAbility:"None", description:"")
Card.create(name:"Vernon Roche", deck:"Northern Realms", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Immune to special", description:"")
Card.create(name:"Ves", deck:"Northern Realms", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Yarpen Zigrin", deck:"Northern Realms", role:"Basic", strength:2, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Barclay Els", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Ciaran aep Easnillien", deck:"Scoia'tael", role:"Basic", strength:3, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Dennis Cranmer", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"None", description:"")
Card.create(name:"Dol Blathanna Archer", deck:"Scoia'tael", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Dol Blathanna Scout", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Dol Blathanna Scout", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Dol Blathanna Scout", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Dwarven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Dwarven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Dwarven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:3, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Eithné", deck:"Scoia'tael", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Elven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:2, combatType:"Range", cardAbility:"Muster", description:"")
Card.create(name:"Elven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:2, combatType:"Range", cardAbility:"Muster", description:"")
Card.create(name:"Elven Skirmisher", deck:"Scoia'tael", role:"Basic", strength:2, combatType:"Range", cardAbility:"Muster", description:"")
Card.create(name:"Filavandrel aen Fidhail", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Francesca Findabair Daisy of The Valley", deck:"Scoia'tael", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Draw extra card", description:"")
Card.create(name:"Francesca Findabair Pureblood Elf", deck:"Scoia'tael", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Frost", description:"")
Card.create(name:"Francesca Findabair Queen of Dol Blath..", deck:"Scoia'tael", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Scorch Close Combat if + 10", description:"")
Card.create(name:"Francesca Findabair the Beautiful", deck:"Scoia'tael", role:"Leaders", strength:0, combatType:"Leader", cardAbility:"Horn on Ranged", description:"")
Card.create(name:"Havekar Healer", deck:"Scoia'tael", role:"Basic", strength:0, combatType:"Range", cardAbility:"Medic", description:"")
Card.create(name:"Havekar Healer", deck:"Scoia'tael", role:"Basic", strength:0, combatType:"Range", cardAbility:"Medic", description:"")
Card.create(name:"Havekar Healer", deck:"Scoia'tael", role:"Basic", strength:0, combatType:"Range", cardAbility:"Medic", description:"")
Card.create(name:"Havekar Smuggler", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Havekar Smuggler", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Havekar Smuggler", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"Muster", description:"")
Card.create(name:"Ida Emean aep Sivney", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Iorveth", deck:"Scoia'tael", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Isengrim Faolitarna", deck:"Scoia'tael", role:"Hero", strength:10, combatType:"Melee", cardAbility:"Morale, Immune to Special", description:"")
Card.create(name:"Mahakaman Defender", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Mahakaman Defender", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Mahakaman Defender", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Mahakaman Defender", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Mahakaman Defender", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee", cardAbility:"None", description:"")
Card.create(name:"Milva", deck:"Scoia'tael", role:"Basic", strength:10, combatType:"Range", cardAbility:"Morale", description:"")
Card.create(name:"Riordain", deck:"Scoia'tael", role:"Basic", strength:1, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Saesenthessis", deck:"Scoia'tael", role:"Hero", strength:10, combatType:"Range", cardAbility:"Immune to special", description:"")
Card.create(name:"Toruviel", deck:"Scoia'tael", role:"Basic", strength:2, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Vrihedd Brigade Recruit", deck:"Scoia'tael", role:"Basic", strength:4, combatType:"Range", cardAbility:"None", description:"")
Card.create(name:"Vrihedd Brigade Veteran", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Vrihedd Brigade Veteran", deck:"Scoia'tael", role:"Basic", strength:5, combatType:"Melee / Range", cardAbility:"Agile", description:"")
Card.create(name:"Yaevinn", deck:"Scoia'tael", role:"Basic", strength:6, combatType:"Melee / Range", cardAbility:"Agile", description:"")

# Test users
User.create(username:"Drake", password:"copperdog1", password_confirmation: "copperdog1", admin: true)
User.create(username:"Bill", password:"Billiam", password_confirmation: "Billiam")
User.create(username:"Frank", password:"I'veCoveredWarsYouKnow", password_confirmation: "I'veCoveredWarsYouKnow")

99.times do |n|
  name    = Faker::Name.name
  password= "password"
  User.create!(username:  name,
               password:               password,
               password_confirmation:  password)
end
# A test deck
Deck.create(deckName:"My First Deck", faction:"Monsters", user:User.find(1))
# A couple of cards in the test deck
DeckCard.create(deck:Deck.find(1), card:Card.find(1))
DeckCard.create(deck:Deck.find(1), card:Card.find(1))
DeckCard.create(deck:Deck.find(1), card:Card.find(2))
  